### ISSUE TITLE
Retain automated backups for RDS on service delete

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/aws-broker#161]
In order to maintain backups as documented,  we want to retain automated snapshots when deleting RDS instances

## Acceptance Criteria
* [x] GIVEN a non-shared RDS service instance \
  WHEN  a user calls cf delete-service on the instance\
  AND the broker finishes deleting the service instance\
  THEN existing, automated backups are still available for 14 days \
  AND existing automated backups are deleted after 15 days

--- 

## Security considerations
Protects data in case of accident or malicious deletion

## Implementation sketch
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DeleteDBInstance.html
* [x] set DeleteAutomatedBackups to false when deleting instances
* [x] validate recoverability
* [x] document recovery process

**Comment by ccostino** [comment]
PR is in place for preserving database backups upon deletion: https://github.com/cloud-gov/aws-broker/pull/168

Once this is reviewed, we'll need to validate this by running the smoke tests or creating a test instance in `dev`, performing a backup and/or letting the automated nightly backup take place, then deleting the instance to make sure the backups are still present.

Once that's validated, we can document how to go about accessing the backup(s) and performing a restore with them.

**Comment by bengerman13** [comment]
FWIW - manual backups are treated differently from automatic backups, so the test here should be by letting automatic backups happen

**Comment by ccostino** [comment]
Thanks for the heads up, @bengerman13!  We'll have to make sure the automated backups take effect then, which will rule out the smoke tests.

**Comment by ccostino** [comment]
Good news!  The broker changes worked and automated backups are preserved in the `Retained` tab of the `Automated Backups` dashboard in the AWS RDS console once an instance is deleted:

<img width="1405" alt="rds-automated-backups" src="https://user-images.githubusercontent.com/121565/117682044-aeb59c80-b180-11eb-90af-8952e0632afb.png">

You have the option of deleting them or restoring to a point in time, which requires you to navigate to a specific snapshot and restoring the snapshot itself.  You have to provide the database identifier as a part of this (because AWS RDS will create a new instance) so there's an opportunity to use the same name as the instance that was deleted.

However, it appears that this will be a new instance (you can't restore into an existing instance), so the broker won't have any knowledge of the DB.  This may be the tricky part.

**Comment by ccostino** [comment]
We're keeping this constrained to documenting the process.  Should this situation arise, we should be working directly with the customer to help with this.  If we find that we need to add this support to the broker itself to pair with a new, restored instance, we should write up a separate ticket for that as it will take some additional time and effort.

PR for the documentation updates are here: https://github.com/cloud-gov/cg-site/pull/1921
